#!/bin/bash

# Turn off cowsay
export ANSIBLE_NOCOWS=1

# Run the playbook using the local hosts file
if [ $1 ];
then
    # Silent for a known working "production" setting 
    # ansible-playbook -i ./hosts -u $1 ./site.yml

    # Verbose for development and lots of output
    ansible-playbook -i ./hosts -vvvv -u $1 ./site.yml
else
    echo "Please append a valid user name to the command."
    echo "Run the command as sudo.  An example would be:"
    echo "sudo ./setup joecool"
fi
