#! /bin/bash
# Install java
sudo apt-get -y purge openjdk*
sudo apt-add-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get -y install oracle-java8-installer
sudo apt-get installirackle-java8-set-default

# Install pycharm
cd /tmp
curl -s -L http://download.jetbrains.com/python/pycharm-community-4.5.1.tar.gz | tar -xz
sudo mv pycharm-4.5.1 /opt/py_devtools/pycharm
/opt/py_devtools/pycharm/bin/pycharm.sh
