---
# file: tasks/miniconda.yml
- hosts: localhost

  tasks:
    # -------------------------------------------------------------------------
    # Download, install miniconda and setup environments
    # -------------------------------------------------------------------------
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # check for existence of miniconda first &
    # set stat for miniconda to check if it exists later
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - stat: path=/opt/pytools/miniconda3
      register: miniconda

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Download miniconda & set permissions
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name:  download miniconda for use later
      command:  curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      when: miniconda.stat.exists == False
      
    - name: change permissions on Miniconda installer
      file:  path=./Miniconda3-latest-Linux-x86_64.sh 
             owner={{ ansible_ssh_user }}
             mode=0775
    
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Install miniconda to /opt/pytools
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: install miniconda
      command: bash ./Miniconda3-latest-Linux-x86_64.sh -b -p /opt/pytools/miniconda3
      when: miniconda.stat.exists == False

    - name: change owner/permission on miniconda installation
      file:  path=/opt/pytools/miniconda3
             state=directory
             recurse=yes
             owner={{ ansible_ssh_user }}
             mode=0775

    - name: remove the Miniconda file from tasks folder
      file:  path=./Miniconda3-latest-Linux-x86_64.sh
             state=absent

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Create various default conda envs
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: add envs_dirs /opt/pytools/envs to condarc
      command:  /opt/pytools/miniconda3/bin/conda config --add envs_dirs /opt/pytools/envs

    - name: create anaconda env
      command:  /opt/pytools/miniconda3/bin/conda create -n anaconda python=3.5 anaconda

    - name: change permissions for all created envs
      file:  path=/opt/pytools/envs
             state=directory
             recurse=yes
             owner={{ ansible_ssh_user }}
             mode=0775

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Update the envs and packages with them
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    - name: update anaconda
      command:  /opt/pytools/envs/anaconda3/bin/conda update --prefix /opt/pytools/envs/anaconda --all
  
