#! /bin/bash
# Upgrade to java8

sudo apt-get install oracle-java8-set-default

# Install pycharm
cd /tmp
curl -s -L http://download.jetbrains.com/python/pycharm-community-4.5.1.tar.gz | tar -xz
sudo mv pycharm-community-4.5.1 /opt/py_devtools/pycharm
/opt/py_devtools/pycharm/bin/pycharm.sh
